name: Build Manager

on:
  workflow_dispatch:
  push:
    branches: [ "main", "dev", "ci" ]
    paths:
      - '.github/workflows/build-manager.yml'
      - '.github/workflows/build-lkm.yml'
      - '.github/workflows/ksud.yml'
      - 'manager/**'
      - 'kernel/**'
      - 'userspace/**'
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - '.github/workflows/build-manager.yml'
      - '.github/workflows/build-lkm.yml'
      - '.github/workflows/ksud.yml'
      - 'manager/**'
      - 'kernel/**'
      - 'userspace/**'
  workflow_call:

jobs:
  build-lkm:
    uses: ./.github/workflows/build-lkm.yml
    secrets: inherit

  build-ksuinit:
    uses: ./.github/workflows/ksuinit.yml

  build-ksud:
    needs: [build-lkm, build-ksuinit]
    strategy:
      matrix:
        include:
          - target: aarch64-linux-android
            os: ubuntu-latest
          - target: x86_64-linux-android
            os: ubuntu-latest
          - target: armv7-linux-androideabi
            os: ubuntu-latest
    uses: ./.github/workflows/ksud.yml
    with:
      target: ${{ matrix.target }}
      os: ${{ matrix.os }}

  build-manager:
    needs: build-ksud
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        spoofed: ["true","false"]
        build_type: ["release","debug"]
    defaults:
      run:
        working-directory: ./manager

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine commit for build
        id: commit
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          else
            echo "COMMIT_SHA=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Determine manager variant
        id: determine
        run: |
          if [ "${{ github.ref_name }}" == "miuix" ] && [ "${{ matrix.spoofed }}" == "true" ]; then
            echo "SKIP=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          if [ "${{ github.ref_name }}" == "miuix" ]; then
            echo "title=Manager" >> $GITHUB_OUTPUT
            echo "topicid=${{ vars.MESSAGE_MIUIX_THREAD_ID }}" >> $GITHUB_OUTPUT
          elif [ "${{ matrix.spoofed }}" == "true" ]; then
            echo "title=Spoofed-Manager" >> $GITHUB_OUTPUT
            echo "topicid=${{ vars.MESSAGE_SPOOFED_THREAD_ID }}" >> $GITHUB_OUTPUT
          else
            echo "title=Manager" >> $GITHUB_OUTPUT
            echo "topicid=${{ vars.MESSAGE_THREAD_ID }}" >> $GITHUB_OUTPUT
          fi

      - name: Run randomizer
        if: ${{ matrix.spoofed == 'true' && steps.determine.outputs.SKIP != 'true' }}
        run: |
          chmod +x randomizer
          ./randomizer

      - name: Write key
        if: ${{ github.event_name == 'workflow_dispatch' || ( github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' )) || github.ref_type == 'tag' }}
        run: |
          if [ ! -z "${{ secrets.KEYSTORE }}" ]; then
            {
              echo KEYSTORE_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}'
              echo KEY_ALIAS='${{ secrets.KEY_ALIAS }}'
              echo KEY_PASSWORD='${{ secrets.KEY_PASSWORD }}'
              echo KEYSTORE_FILE='key.jks'
            } >> gradle.properties
            echo "${{ secrets.KEYSTORE }}" | base64 -d > key.jks
          fi

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Download arm64 ksud
        uses: actions/download-artifact@v4
        with:
          name: ksud-aarch64-linux-android
          path: .

      - name: Download x86_64 ksud
        uses: actions/download-artifact@v4
        with:
          name: ksud-x86_64-linux-android
          path: .

      - name: Download arm ksud
        uses: actions/download-artifact@v4
        with:
          name: ksud-armv7-linux-androideabi
          path: .

      - name: Copy ksud to app jniLibs
        run: |
          mkdir -p app/src/main/jniLibs/arm64-v8a
          mkdir -p app/src/main/jniLibs/x86_64
          mkdir -p app/src/main/jniLibs/armeabi-v7a
          cp -f ../aarch64-linux-android/release/ksud ../manager/app/src/main/jniLibs/arm64-v8a/libksud.so
          cp -f ../x86_64-linux-android/release/ksud ../manager/app/src/main/jniLibs/x86_64/libksud.so
          cp -f ../armv7-linux-androideabi/release/ksud ../manager/app/src/main/jniLibs/armeabi-v7a/libksud.so

      - name: Build APK
        run: ./gradlew assemble${{ matrix.build_type }} -Pcommit=${{ steps.commit.outputs.COMMIT_SHA }} --configuration-cache

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.determine.outputs.title }}-${{ matrix.build_type }}
          path: |
            manager/app/build/outputs/apk/release/*.apk
            manager/app/build/outputs/mapping/release/
            manager/app/build/outputs/apk/debug/*.apk

  upload-telegram:
    needs: build-manager
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spoofed: ["true","false"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup need_upload
        id: need_upload
        run: |
          if [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
            echo "UPLOAD=true" >> $GITHUB_OUTPUT
          else
            echo "UPLOAD=false" >> $GITHUB_OUTPUT
          fi

      - name: Determine commit info
        id: commit
        run: |
          echo "SHA=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          if [ "${{ github.event_name }}" = "push" ] && [ -n "${{ github.event.head_commit.message }}" ]; then
            MSG="${{ github.event.head_commit.message }}"
          else
            MSG="$(git log -1 --pretty=%B)"
          fi
          cat <<EOF >> "$GITHUB_OUTPUT"
          MESSAGE<<MESSAGE_EOF
          $MSG
          MESSAGE_EOF
          EOF
          echo "URL=${{ github.server_url }}/${{ github.repository }}/commit/$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Determine manager variant
        id: determine
        run: |
          if [ "${{ github.ref_name }}" == "miuix" ] && [ "${{ matrix.spoofed }}" == "true" ]; then
            echo "SKIP=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          if [ "${{ github.ref_name }}" == "miuix" ]; then
            echo "title=Manager" >> $GITHUB_OUTPUT
            echo "topicid=${{ vars.MESSAGE_MIUIX_THREAD_ID }}" >> $GITHUB_OUTPUT
          elif [ "${{ matrix.spoofed }}" == "true" ]; then
            echo "title=Spoofed-Manager" >> $GITHUB_OUTPUT
            echo "topicid=${{ vars.MESSAGE_SPOOFED_THREAD_ID }}" >> $GITHUB_OUTPUT
          else
            echo "title=Manager" >> $GITHUB_OUTPUT
            echo "topicid=${{ vars.MESSAGE_THREAD_ID }}" >> $GITHUB_OUTPUT
          fi
        
      - name: Download Debug artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ steps.determine.outputs.title }}-debug
          path: .

      - name: Download Release artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ steps.determine.outputs.title }}-release
          path: .

      - name: Make captain
        if: github.event_name != 'pull_request' && steps.need_upload.outputs.UPLOAD == 'true' && steps.determine.outputs.SKIP != 'true'
        env:
          COMMIT_MESSAGE: ${{ steps.commit.outputs.MESSAGE }}
          COMMIT_URL: ${{ steps.commit.outputs.URL }} 
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          TITLE: ${{ steps.determine.outputs.title }}
          BRANCH: ${{ github.ref_name }}
        run: |
           #!/bin/bash
           MSG_CONTENT="**${TITLE}**
           Branch: ${BRANCH}
           #ci_${VERSION}
           \`\`\`
           ${COMMIT_MESSAGE}
           \`\`\`
           [Commit](${COMMIT_URL})
           [Workflow run](${RUN_URL})"
           echo "$MSG_CONTENT"
           echo "$MSG_CONTENT" > caption.txt
      - name: Upload to Telegram
        uses: PuerNya/tg-bot-upload@v1
        with:
          bot-id: ${{ secrets.BOT_TOKEN }}
          chat-id: ${{ vars.CHAT_ID }}
          topic-id: ${{ steps.determine.outputs.topicid }}
          file-path: caption.txt